version: '3.8'
services:
  postgres:
    image: postgres:latest 
    container_name: postgres_brt
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: brt_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Volume correto

volumes:
  postgres_data: {}  # Definição do volume fora de "services"
